FINDO-8184_update_schema
findologic/xml-response-schema pull request #1
Opened 2019-06-05 14:37 UTC by TheKeymaster

2019-06-11 10:14 UTC, wladi0097 reviewed
Some minor stuff

2019-06-11 10:14 UTC, wladi0097 commented on schema.xsd
> +    <!-- Range slider filters. Filters "min"/"max" may not have any values if there is nothing to filter for. -->
'... any values if there is nothing to filter for.' -> '... any values if there is nothing to filter'

2019-06-11 10:14 UTC, wladi0097 commented on schema.xsd
> +                                    <xs:attribute name="count" type="xs:integer" use="required"/>
Can it be a negative value ? Use `xs:nonNegativeInteger` is not.

2019-06-11 10:14 UTC, wladi0097 commented on schema.xsd
> +                        <xs:pattern value="^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$"/>
Please explain what the regex is doing in a comment above it

2019-06-17 09:55 UTC, howard requested changes

2019-06-17 09:55 UTC, howard commented on schema.xsd
> +                <xs:simpleType>
Define this union type as a separate named one, as we do it with `range`, because it's used in multiple places.

2019-06-17 09:55 UTC, howard commented on schema.xsd
> +            <xs:element name="itemCount" type="xs:int" minOccurs="0" maxOccurs="1" />
`1` is the default value of `maxOccurs`, so it shouldn't be necessary to specify it explicitly.

2019-06-17 09:55 UTC, howard commented on schema.xsd
> +            <xs:element name="cssClass" type="xs:string" minOccurs="0" maxOccurs="1" />
`1` is the default value of `maxOccurs`, so it shouldn't be necessary to specify it explicitly.

2019-06-17 09:55 UTC, howard commented on schema.xsd
> +            <xs:element name="noAvailableFiltersText" type="xs:string" minOccurs="0" maxOccurs="1" />
`1` is the default value of `maxOccurs`, so it shouldn't be necessary to specify it explicitly.

2019-06-17 09:55 UTC, howard commented on schema.xsd
> +                                    <xs:element name="frequency" type="xs:nonNegativeInteger" minOccurs="0" maxOccurs="1" />
`1` is the default value of `maxOccurs`, so it shouldn't be necessary to specify it explicitly.

2019-06-17 09:55 UTC, howard commented on schema.xsd
> +                                    <xs:element name="selected" minOccurs="0" maxOccurs="1" />
`1` is the default value of `maxOccurs`, so it shouldn't be necessary to specify it explicitly.

2019-06-17 09:55 UTC, howard commented on schema.xsd
> +                                    <xs:element name="parameters" type="range" minOccurs="0" maxOccurs="1" />
`1` is the default value of `maxOccurs`, so it shouldn't be necessary to specify it explicitly.

2019-06-17 09:55 UTC, howard commented on schema.xsd
> +                                    <xs:element name="color" minOccurs="0" maxOccurs="1" />
`1` is the default value of `maxOccurs`, so it shouldn't be necessary to specify it explicitly.

2019-06-17 09:55 UTC, howard commented on schema.xsd
> +                                    <xs:element name="image" type="xs:anyURI" minOccurs="0" maxOccurs="1" />
`1` is the default value of `maxOccurs`, so it shouldn't be necessary to specify it explicitly.

2019-06-24 07:38 UTC, howard approved these changes

2019-06-24 07:39 UTC, merged